-------------Error at 06/10/2021 05:54:12------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 06/10/2021 05:54:12------------- 

-------------Fatal at 06/10/2021 05:54:16------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : The requested address is not valid in its context
 Source: System -> Void DoBind(System.Net.EndPoint, System.Net.SocketAddress)
 Stack Trace:
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Stump.Server.AuthServer.IPC.IPCHost.Start() in C:\Users\Administrator\Desktop\httpdocs\ff\server\Stump.Server.AuthServer\IPC\IPCHost.cs:line 121
   at Stump.Server.AuthServer.AuthServer.Start() in C:\Users\Administrator\Desktop\httpdocs\ff\server\Stump.Server.AuthServer\AuthServer.cs:line 155
   at Stump.GUI.AuthConsole.Program.Main(String[] args) in C:\Users\Administrator\Desktop\httpdocs\ff\GUI\Stump.GUI.AuthConsole\Program.cs:line 21 
-------------Fatal at 06/10/2021 05:54:16------------- 

-------------Error at 06/10/2021 05:55:42------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 06/10/2021 05:55:42------------- 

-------------Error at 06/10/2021 06:18:09------------- 
 Stump.Server.AuthServer.IPC.IPCClient.SendError -> 
	IPC error : {0} 
-------------Error at 06/10/2021 06:18:09------------- 

-------------Error at 06/10/2021 06:48:15------------- 
 Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback -> 
	Exception raised when processing TimerEntry Stump.Core.Timers.TimedTimerEntry (Callback = Stump.Server.AuthServer.AuthServer.Void DisconnectAfkClient(), Delay = 225000) in Stump.Server.BaseServer.Benchmark.BenchmarkedTaskPool : System.NullReferenceException: Object reference not set to an instance of an object.
   at Stump.Core.Collections.LimitedStack`1.Peek() in C:\Users\Administrator\Desktop\httpdocs\ff\Core\Stump.Core\Collections\LimitedStack.cs:line 37
   at Stump.Server.BaseServer.Network.BaseClient.get_LastActivity() in C:\Users\Administrator\Desktop\httpdocs\ff\server\Stump.Server.BaseServer\Network\BaseClient.cs:line 96
   at Stump.Server.BaseServer.ServerBase.<>c.<DisconnectAfkClient>b__112_0(BaseClient client) in C:\Users\Administrator\Desktop\httpdocs\ff\server\Stump.Server.BaseServer\ServerBase.cs:line 484
   at Stump.Server.BaseServer.Network.ClientManager.<>c__DisplayClass58_0.<FindAll>b__0(BaseClient entry) in C:\Users\Administrator\Desktop\httpdocs\ff\server\Stump.Server.BaseServer\Network\ClientManager.cs:line 340
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Stump.Server.BaseServer.Network.ClientManager.FindAll(Predicate`1 predicate) in C:\Users\Administrator\Desktop\httpdocs\ff\server\Stump.Server.BaseServer\Network\ClientManager.cs:line 340
   at Stump.Server.BaseServer.ServerBase.DisconnectAfkClient() in C:\Users\Administrator\Desktop\httpdocs\ff\server\Stump.Server.BaseServer\ServerBase.cs:line 483
   at Stump.Core.Timers.TimedTimerEntry.Trigger() in C:\Users\Administrator\Desktop\httpdocs\ff\Core\Stump.Core\Timers\TimedTimerEntry.cs:line 128
   at Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback(Object state) in C:\Users\Administrator\Desktop\httpdocs\ff\Core\Stump.Core\Threading\SelfRunningTaskPool.cs:line 223. 
-------------Error at 06/10/2021 06:48:15------------- 

-------------Error at 06/10/2021 22:11:52------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 06/10/2021 22:11:52------------- 

-------------Fatal at 06/10/2021 22:11:54------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at Stump.ORM.Database.OpenSharedConnection() in C:\Users\Administrator\Desktop\httpdocs\ff\Core\Stump.ORM\PetaPoco.cs:line 243
   at Stump.ORM.DatabaseAccessor.OpenConnection(Database database) in C:\Users\Administrator\Desktop\httpdocs\ff\Core\Stump.ORM\DatabaseAccessor.cs:line 106
   at Stump.ORM.DatabaseAccessor.OpenConnection() in C:\Users\Administrator\Desktop\httpdocs\ff\Core\Stump.ORM\DatabaseAccessor.cs:line 140
   at Stump.Server.AuthServer.AuthServer.Initialize() in C:\Users\Administrator\Desktop\httpdocs\ff\server\Stump.Server.AuthServer\AuthServer.cs:line 109 
-------------Fatal at 06/10/2021 22:11:54------------- 

-------------Fatal at 06/10/2021 22:11:54------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : One or more errors occurred.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings, MyNetworkStream& networkStream)
   at MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings, MyNetworkStream& networkStream)
   at MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 06/10/2021 22:11:54------------- 

-------------Fatal at 06/10/2021 22:11:54------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : No connection could be made because the target machine actively refused it 127.0.0.1:3306
 Source: System -> Void InternalEndConnect(System.IAsyncResult)
 Stack Trace:
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 06/10/2021 22:11:54------------- 

-------------Error at 06/10/2021 22:12:07------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 06/10/2021 22:12:07------------- 

-------------Fatal at 06/10/2021 22:12:08------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at Stump.ORM.Database.OpenSharedConnection() in C:\Users\Administrator\Desktop\httpdocs\ff\Core\Stump.ORM\PetaPoco.cs:line 243
   at Stump.ORM.DatabaseAccessor.OpenConnection(Database database) in C:\Users\Administrator\Desktop\httpdocs\ff\Core\Stump.ORM\DatabaseAccessor.cs:line 106
   at Stump.ORM.DatabaseAccessor.OpenConnection() in C:\Users\Administrator\Desktop\httpdocs\ff\Core\Stump.ORM\DatabaseAccessor.cs:line 140
   at Stump.Server.AuthServer.AuthServer.Initialize() in C:\Users\Administrator\Desktop\httpdocs\ff\server\Stump.Server.AuthServer\AuthServer.cs:line 109 
-------------Fatal at 06/10/2021 22:12:08------------- 

-------------Fatal at 06/10/2021 22:12:08------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : One or more errors occurred.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings, MyNetworkStream& networkStream)
   at MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings, MyNetworkStream& networkStream)
   at MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 06/10/2021 22:12:08------------- 

-------------Fatal at 06/10/2021 22:12:08------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : No connection could be made because the target machine actively refused it 127.0.0.1:3306
 Source: System -> Void InternalEndConnect(System.IAsyncResult)
 Stack Trace:
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 06/10/2021 22:12:08------------- 

-------------Error at 06/10/2021 22:12:39------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 06/10/2021 22:12:39------------- 

