-------------Error at 02/11/2018 02:14:04------------- 
 Stump.Server.BaseServer.Network.BaseClient.ProcessReceive -> 
	Forced disconnection <189.212.229.210> : System.ArgumentOutOfRangeException: L'argument spécifié n'était pas dans les limites de la plage des valeurs valides.
Nom du paramètre : Required buffer is way too big: 5111904
   à Stump.Core.Pool.BufferManager.GetSegment(Int32 payloadSize, Boolean allowExceed) dans C:\Users\Administrateur\Desktop\calistya\Core\Stump.Core\Pool\BufferManager.cs:ligne 479
   à Stump.Server.BaseServer.Network.BaseClient.EnsureBuffer(Int32 length) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 326
   à Stump.Server.BaseServer.Network.BaseClient.BuildMessage(BufferSegment buffer) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 314
   à Stump.Server.BaseServer.Network.BaseClient.ProcessReceive(Object sender, SocketAsyncEventArgs args) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 223 
-------------Error at 02/11/2018 02:14:04------------- 

-------------Error at 02/11/2018 05:05:10------------- 
 Stump.Server.BaseServer.Network.BaseClient.ProcessReceive -> 
	Forced disconnection <71.6.146.130> : Stump.DofusProtocol.Messages.MessageReceiver+MessageNotFoundException: Message <id:1408> doesn't exist
   à Stump.DofusProtocol.Messages.MessageReceiver.BuildMessage(UInt32 id, IDataReader reader) dans C:\Users\Administrateur\Desktop\calistya\DofusProtocol\Messages\MessageReceiver.cs:ligne 74
   à Stump.Server.BaseServer.Network.BaseClient.BuildMessage(BufferSegment buffer) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 279
   à Stump.Server.BaseServer.Network.BaseClient.ProcessReceive(Object sender, SocketAsyncEventArgs args) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 223 
-------------Error at 02/11/2018 05:05:10------------- 

-------------Error at 02/11/2018 10:35:48------------- 
 Stump.Server.BaseServer.Network.BaseClient.ProcessReceive -> 
	Forced disconnection <91.229.20.4> : Stump.DofusProtocol.Messages.MessageReceiver+MessageNotFoundException: Message <id:1408> doesn't exist
   à Stump.DofusProtocol.Messages.MessageReceiver.BuildMessage(UInt32 id, IDataReader reader) dans C:\Users\Administrateur\Desktop\calistya\DofusProtocol\Messages\MessageReceiver.cs:ligne 74
   à Stump.Server.BaseServer.Network.BaseClient.BuildMessage(BufferSegment buffer) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 279
   à Stump.Server.BaseServer.Network.BaseClient.ProcessReceive(Object sender, SocketAsyncEventArgs args) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 223 
-------------Error at 02/11/2018 10:35:48------------- 

-------------Error at 02/11/2018 10:35:48------------- 
 Stump.Server.BaseServer.Network.BaseClient.ProcessReceive -> 
	Forced disconnection <91.229.20.4> : Stump.DofusProtocol.Messages.MessageReceiver+MessageNotFoundException: Message <id:1408> doesn't exist
   à Stump.DofusProtocol.Messages.MessageReceiver.BuildMessage(UInt32 id, IDataReader reader) dans C:\Users\Administrateur\Desktop\calistya\DofusProtocol\Messages\MessageReceiver.cs:ligne 74
   à Stump.Server.BaseServer.Network.BaseClient.BuildMessage(BufferSegment buffer) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 279
   à Stump.Server.BaseServer.Network.BaseClient.ProcessReceive(Object sender, SocketAsyncEventArgs args) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 223 
-------------Error at 02/11/2018 10:35:48------------- 

-------------Error at 02/11/2018 10:35:53------------- 
 Stump.Server.BaseServer.Network.BaseClient.ProcessReceive -> 
	Forced disconnection <91.229.20.4> : Stump.DofusProtocol.Messages.MessageReceiver+MessageNotFoundException: Message <id:6912> doesn't exist
   à Stump.DofusProtocol.Messages.MessageReceiver.BuildMessage(UInt32 id, IDataReader reader) dans C:\Users\Administrateur\Desktop\calistya\DofusProtocol\Messages\MessageReceiver.cs:ligne 74
   à Stump.Server.BaseServer.Network.BaseClient.BuildMessage(BufferSegment buffer) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 279
   à Stump.Server.BaseServer.Network.BaseClient.ProcessReceive(Object sender, SocketAsyncEventArgs args) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 223 
-------------Error at 02/11/2018 10:35:53------------- 

-------------Error at 02/11/2018 10:35:58------------- 
 Stump.Server.BaseServer.Network.BaseClient.ProcessReceive -> 
	Forced disconnection <91.229.20.4> : System.InvalidOperationException: Buffer overflow
   à Stump.Core.IO.FastBigEndianReader.set_Position(Int64 value) dans C:\Users\Administrateur\Desktop\calistya\Core\Stump.Core\IO\FastBigEndianReader.cs:ligne 54
   à Stump.Core.IO.FastBigEndianReader.ReadInt() dans C:\Users\Administrateur\Desktop\calistya\Core\Stump.Core\IO\FastBigEndianReader.cs:ligne 214
   à Stump.Core.IO.FastBigEndianReader.ReadUInt() dans C:\Users\Administrateur\Desktop\calistya\Core\Stump.Core\IO\FastBigEndianReader.cs:ligne 240
   à Stump.Server.BaseServer.Network.MessagePart.Build(IDataReader reader) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\MessagePart.cs:ligne 99
   à Stump.Server.BaseServer.Network.BaseClient.BuildMessage(BufferSegment buffer) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 259
   à Stump.Server.BaseServer.Network.BaseClient.ProcessReceive(Object sender, SocketAsyncEventArgs args) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 223 
-------------Error at 02/11/2018 10:35:58------------- 

-------------Error at 02/11/2018 15:46:30------------- 
 Stump.Server.BaseServer.Network.BaseClient.ProcessReceive -> 
	Forced disconnection <74.82.47.3> : Stump.DofusProtocol.Messages.MessageReceiver+MessageNotFoundException: Message <id:1408> doesn't exist
   à Stump.DofusProtocol.Messages.MessageReceiver.BuildMessage(UInt32 id, IDataReader reader) dans C:\Users\Administrateur\Desktop\calistya\DofusProtocol\Messages\MessageReceiver.cs:ligne 74
   à Stump.Server.BaseServer.Network.BaseClient.BuildMessage(BufferSegment buffer) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 279
   à Stump.Server.BaseServer.Network.BaseClient.ProcessReceive(Object sender, SocketAsyncEventArgs args) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 223 
-------------Error at 02/11/2018 15:46:30------------- 

-------------Error at 02/11/2018 16:29:37------------- 
 Stump.Server.BaseServer.Network.BaseClient.ProcessReceive -> 
	Forced disconnection <141.212.122.32> : Stump.DofusProtocol.Messages.MessageReceiver+MessageNotFoundException: Message <id:1408> doesn't exist
   à Stump.DofusProtocol.Messages.MessageReceiver.BuildMessage(UInt32 id, IDataReader reader) dans C:\Users\Administrateur\Desktop\calistya\DofusProtocol\Messages\MessageReceiver.cs:ligne 74
   à Stump.Server.BaseServer.Network.BaseClient.BuildMessage(BufferSegment buffer) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 279
   à Stump.Server.BaseServer.Network.BaseClient.ProcessReceive(Object sender, SocketAsyncEventArgs args) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 223 
-------------Error at 02/11/2018 16:29:37------------- 

-------------Error at 02/11/2018 16:35:58------------- 
 Stump.Server.BaseServer.Network.BaseClient.ProcessReceive -> 
	Forced disconnection <172.104.115.143> : Stump.DofusProtocol.Messages.MessageReceiver+MessageNotFoundException: Message <id:1408> doesn't exist
   à Stump.DofusProtocol.Messages.MessageReceiver.BuildMessage(UInt32 id, IDataReader reader) dans C:\Users\Administrateur\Desktop\calistya\DofusProtocol\Messages\MessageReceiver.cs:ligne 74
   à Stump.Server.BaseServer.Network.BaseClient.BuildMessage(BufferSegment buffer) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 279
   à Stump.Server.BaseServer.Network.BaseClient.ProcessReceive(Object sender, SocketAsyncEventArgs args) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 223 
-------------Error at 02/11/2018 16:35:58------------- 

-------------Error at 02/11/2018 19:19:59------------- 
 Stump.Server.BaseServer.Network.BaseClient.ProcessReceive -> 
	Forced disconnection <50.116.3.158> : Stump.DofusProtocol.Messages.MessageReceiver+MessageNotFoundException: Message <id:1408> doesn't exist
   à Stump.DofusProtocol.Messages.MessageReceiver.BuildMessage(UInt32 id, IDataReader reader) dans C:\Users\Administrateur\Desktop\calistya\DofusProtocol\Messages\MessageReceiver.cs:ligne 74
   à Stump.Server.BaseServer.Network.BaseClient.BuildMessage(BufferSegment buffer) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 279
   à Stump.Server.BaseServer.Network.BaseClient.ProcessReceive(Object sender, SocketAsyncEventArgs args) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 223 
-------------Error at 02/11/2018 19:19:59------------- 

-------------Error at 02/11/2018 23:31:45------------- 
 Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback -> 
	Exception raised when processing TimerEntry Stump.Core.Timers.TimedTimerEntry (Callback = Stump.Server.AuthServer.AuthServer.Void DisconnectAfkClient(), Delay = 225000) in Stump.Server.BaseServer.Benchmark.BenchmarkedTaskPool : System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à Stump.Core.Collections.LimitedStack`1.Peek() dans C:\Users\Administrateur\Desktop\calistya\Core\Stump.Core\Collections\LimitedStack.cs:ligne 37
   à Stump.Server.BaseServer.Network.BaseClient.get_LastActivity() dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\BaseClient.cs:ligne 93
   à Stump.Server.BaseServer.ServerBase.<>c.<DisconnectAfkClient>b__112_0(BaseClient client) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\ServerBase.cs:ligne 484
   à Stump.Server.BaseServer.Network.ClientManager.<>c__DisplayClass58_0.<FindAll>b__0(BaseClient entry) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\ClientManager.cs:ligne 340
   à System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   à System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   à System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   à Stump.Server.BaseServer.Network.ClientManager.FindAll(Predicate`1 predicate) dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\Network\ClientManager.cs:ligne 340
   à Stump.Server.BaseServer.ServerBase.DisconnectAfkClient() dans C:\Users\Administrateur\Desktop\calistya\server\Stump.Server.BaseServer\ServerBase.cs:ligne 483
   à Stump.Core.Timers.TimedTimerEntry.Trigger() dans C:\Users\Administrateur\Desktop\calistya\Core\Stump.Core\Timers\TimedTimerEntry.cs:ligne 128
   à Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback(Object state) dans C:\Users\Administrateur\Desktop\calistya\Core\Stump.Core\Threading\SelfRunningTaskPool.cs:ligne 223. 
-------------Error at 02/11/2018 23:31:45------------- 

