-------------Error at 04/17/2020 09:58:48------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 09:58:48------------- 

-------------Error at 04/17/2020 10:05:20------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 10:05:20------------- 

-------------Fatal at 04/17/2020 10:05:27------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une seule utilisation de chaque adresse de socket (protocole/adresse réseau/port) est habituellement autorisée
 Source: System -> Void DoBind(System.Net.EndPoint, System.Net.SocketAddress)
 Stack Trace:
   à System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   à System.Net.Sockets.Socket.Bind(EndPoint localEP)
   à Stump.Server.AuthServer.IPC.IPCHost.Start() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\IPC\IPCHost.cs:ligne 121
   à Stump.Server.AuthServer.AuthServer.Start() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 155
   à Stump.GUI.AuthConsole.Program.Main(String[] args) dans C:\Users\Ordinateur\Desktop\Decay 2.51\GUI\Stump.GUI.AuthConsole\Program.cs:ligne 21 
-------------Fatal at 04/17/2020 10:05:27------------- 

-------------Error at 04/17/2020 13:41:17------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 13:41:17------------- 

-------------Error at 04/17/2020 13:42:05------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 13:42:05------------- 

-------------Error at 04/17/2020 14:38:59------------- 
 Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback -> 
	Exception raised when processing TimerEntry Stump.Core.Timers.TimedTimerEntry (Callback = Stump.Server.AuthServer.Managers.AccountManager.Void RefreshBans(), Delay = 60000) in Stump.Server.BaseServer.Benchmark.BenchmarkedTaskPool : MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered during command execution. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered attempting to read the resultset. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Reading from the stream has failed. ---> System.IO.IOException: Impossible de lire les données de la connexion de transport : Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu. ---> System.Net.Sockets.SocketException: Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu
   à System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   à System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   à System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   à System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   à MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   à MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   à MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   à MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   à MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   à MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   à MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   à MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   à MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   à MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   à System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   à Stump.ORM.Database.<Query>d__71`1.MoveNext() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 783
   à System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   à System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   à Stump.Server.AuthServer.Managers.AccountManager.RefreshBans() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\Managers\AccountManager.cs:ligne 96
   à Stump.Core.Timers.TimedTimerEntry.Trigger() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Timers\TimedTimerEntry.cs:ligne 128
   à Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback(Object state) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Threading\SelfRunningTaskPool.cs:ligne 223. 
-------------Error at 04/17/2020 14:38:59------------- 

-------------Error at 04/17/2020 14:39:31------------- 
 Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback -> 
	Exception raised when processing TimerEntry Stump.Core.Timers.TimedTimerEntry (Callback = Stump.Server.AuthServer.Managers.AccountManager.Void RefreshBans(), Delay = 60000) in Stump.Server.BaseServer.Benchmark.BenchmarkedTaskPool : MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered during command execution. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered attempting to read the resultset. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Reading from the stream has failed. ---> System.IO.IOException: Impossible de lire les données de la connexion de transport : Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu. ---> System.Net.Sockets.SocketException: Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu
   à System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   à System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   à System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   à System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   à MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   à MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   à MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   à MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   à MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   à MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   à MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   à MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   à MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   à MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   à System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   à Stump.ORM.Database.<Query>d__71`1.MoveNext() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 783
   à System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   à System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   à Stump.Server.AuthServer.Managers.AccountManager.RefreshBans() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\Managers\AccountManager.cs:ligne 96
   à Stump.Core.Timers.TimedTimerEntry.Trigger() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Timers\TimedTimerEntry.cs:ligne 128
   à Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback(Object state) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Threading\SelfRunningTaskPool.cs:ligne 223. 
-------------Error at 04/17/2020 14:39:31------------- 

-------------Error at 04/17/2020 14:39:31------------- 
 Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback -> 
	Exception raised when processing TimerEntry Stump.Core.Timers.TimedTimerEntry (Callback = Stump.Server.AuthServer.Managers.AccountManager.Void RefreshBans(), Delay = 60000) in Stump.Server.BaseServer.Benchmark.BenchmarkedTaskPool : System.InvalidOperationException: Connection must be valid and open.
   à MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   à MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   à MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   à MySql.Data.MySqlClient.MySqlCommand.CheckState()
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   à System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   à Stump.ORM.Database.<Query>d__71`1.MoveNext() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 783
   à System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   à System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   à Stump.Server.AuthServer.Managers.AccountManager.RefreshBans() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\Managers\AccountManager.cs:ligne 96
   à Stump.Core.Timers.TimedTimerEntry.Trigger() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Timers\TimedTimerEntry.cs:ligne 128
   à Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback(Object state) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Threading\SelfRunningTaskPool.cs:ligne 223. 
-------------Error at 04/17/2020 14:39:31------------- 

-------------Error at 04/17/2020 14:39:31------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 14:39:31------------- 

-------------Warn at 04/17/2020 14:39:31------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 14:39:31------------- 

-------------Error at 04/17/2020 14:39:46------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 14:39:46------------- 

-------------Error at 04/17/2020 14:40:11------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 14:40:11------------- 

-------------Warn at 04/17/2020 14:40:11------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 14:40:11------------- 

-------------Error at 04/17/2020 14:40:26------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 14:40:26------------- 

-------------Error at 04/17/2020 14:40:51------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 14:40:51------------- 

-------------Warn at 04/17/2020 14:40:51------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 14:40:51------------- 

-------------Error at 04/17/2020 14:41:06------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 14:41:06------------- 

-------------Error at 04/17/2020 14:41:28------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 14:41:28------------- 

-------------Warn at 04/17/2020 14:41:28------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 14:41:28------------- 

-------------Error at 04/17/2020 14:41:28------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 14:41:28------------- 

-------------Error at 04/17/2020 14:41:38------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 14:41:38------------- 

-------------Warn at 04/17/2020 14:41:38------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 14:41:38------------- 

-------------Error at 04/17/2020 14:41:38------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 14:41:38------------- 

-------------Error at 04/17/2020 14:41:48------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 14:41:48------------- 

-------------Warn at 04/17/2020 14:41:48------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 14:41:48------------- 

-------------Error at 04/17/2020 14:41:48------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 14:41:48------------- 

-------------Error at 04/17/2020 14:42:09------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 14:42:09------------- 

-------------Warn at 04/17/2020 14:42:09------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 14:42:09------------- 

-------------Error at 04/17/2020 14:42:10------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 14:42:10------------- 

-------------Error at 04/17/2020 14:42:21------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 14:42:21------------- 

-------------Warn at 04/17/2020 14:42:21------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 14:42:21------------- 

-------------Error at 04/17/2020 14:42:21------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 14:42:21------------- 

-------------Error at 04/17/2020 14:42:31------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 14:42:31------------- 

-------------Warn at 04/17/2020 14:42:31------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 14:42:31------------- 

-------------Error at 04/17/2020 14:42:31------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 14:42:31------------- 

-------------Error at 04/17/2020 14:42:41------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 14:42:41------------- 

-------------Warn at 04/17/2020 14:42:41------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 14:42:41------------- 

-------------Error at 04/17/2020 14:42:41------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 14:42:41------------- 

-------------Error at 04/17/2020 14:42:53------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 14:42:53------------- 

-------------Warn at 04/17/2020 14:42:53------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 14:42:53------------- 

-------------Error at 04/17/2020 14:42:53------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 14:42:53------------- 

-------------Error at 04/17/2020 14:43:01------------- 
 Stump.Server.AuthServer.IPC.IPCClient.SendError -> 
	IPC error : {0} 
-------------Error at 04/17/2020 14:43:01------------- 

-------------Error at 04/17/2020 14:43:03------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 14:43:03------------- 

-------------Warn at 04/17/2020 14:43:03------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 14:43:03------------- 

-------------Error at 04/17/2020 14:43:03------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 14:43:03------------- 

-------------Error at 04/17/2020 14:43:25------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 14:43:25------------- 

-------------Warn at 04/17/2020 14:43:25------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 14:43:25------------- 

-------------Error at 04/17/2020 14:43:25------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 14:43:25------------- 

-------------Fatal at 04/17/2020 14:43:25------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Aucune exception de tâche n'a été observée en attendant la tâche ou en accédant à sa propriété Exception. Par conséquent, l'exception non prise en charge a été à nouveau levée par le thread finaliseur.
 Source:  -> 
 Stack Trace:
 
-------------Fatal at 04/17/2020 14:43:25------------- 

-------------Fatal at 04/17/2020 14:43:25------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu 185.31.40.59:3306
 Source: System -> Void InternalEndConnect(System.IAsyncResult)
 Stack Trace:
   à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   à System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 14:43:25------------- 

-------------Fatal at 04/17/2020 14:43:25------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Aucune exception de tâche n'a été observée en attendant la tâche ou en accédant à sa propriété Exception. Par conséquent, l'exception non prise en charge a été à nouveau levée par le thread finaliseur.
 Source:  -> 
 Stack Trace:
 
-------------Fatal at 04/17/2020 14:43:25------------- 

-------------Fatal at 04/17/2020 14:43:25------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu 185.31.40.59:3306
 Source: System -> Void InternalEndConnect(System.IAsyncResult)
 Stack Trace:
   à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   à System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 14:43:25------------- 

-------------Fatal at 04/17/2020 14:43:25------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Aucune exception de tâche n'a été observée en attendant la tâche ou en accédant à sa propriété Exception. Par conséquent, l'exception non prise en charge a été à nouveau levée par le thread finaliseur.
 Source:  -> 
 Stack Trace:
 
-------------Fatal at 04/17/2020 14:43:25------------- 

-------------Fatal at 04/17/2020 14:43:25------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu 185.31.40.59:3306
 Source: System -> Void InternalEndConnect(System.IAsyncResult)
 Stack Trace:
   à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   à System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 14:43:25------------- 

-------------Fatal at 04/17/2020 14:43:25------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Aucune exception de tâche n'a été observée en attendant la tâche ou en accédant à sa propriété Exception. Par conséquent, l'exception non prise en charge a été à nouveau levée par le thread finaliseur.
 Source:  -> 
 Stack Trace:
 
-------------Fatal at 04/17/2020 14:43:25------------- 

-------------Fatal at 04/17/2020 14:43:25------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu 185.31.40.59:3306
 Source: System -> Void InternalEndConnect(System.IAsyncResult)
 Stack Trace:
   à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   à System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 14:43:25------------- 

-------------Fatal at 04/17/2020 14:43:25------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Aucune exception de tâche n'a été observée en attendant la tâche ou en accédant à sa propriété Exception. Par conséquent, l'exception non prise en charge a été à nouveau levée par le thread finaliseur.
 Source:  -> 
 Stack Trace:
 
-------------Fatal at 04/17/2020 14:43:25------------- 

-------------Fatal at 04/17/2020 14:43:25------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu 185.31.40.59:3306
 Source: System -> Void InternalEndConnect(System.IAsyncResult)
 Stack Trace:
   à System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   à System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   à System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 14:43:25------------- 

-------------Error at 04/17/2020 14:59:44------------- 
 Stump.Server.AuthServer.IPC.IPCClient.SendError -> 
	IPC error : {0} 
-------------Error at 04/17/2020 14:59:44------------- 

-------------Error at 04/17/2020 15:02:23------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 15:02:23------------- 

-------------Error at 04/17/2020 15:23:50------------- 
 Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback -> 
	Exception raised when processing TimerEntry Stump.Core.Timers.TimedTimerEntry (Callback = Stump.Server.AuthServer.Managers.AccountManager.Void RefreshBans(), Delay = 60000) in Stump.Server.BaseServer.Benchmark.BenchmarkedTaskPool : MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered during command execution. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered attempting to read the resultset. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Reading from the stream has failed. ---> System.IO.IOException: Impossible de lire les données de la connexion de transport : Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu. ---> System.Net.Sockets.SocketException: Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu
   à System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   à System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   à System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   à System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   à MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   à MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   à MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   à MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   à MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   à MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   à MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   à MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   à MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   à MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   à System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   à Stump.ORM.Database.<Query>d__71`1.MoveNext() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 783
   à System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   à System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   à Stump.Server.AuthServer.Managers.AccountManager.RefreshBans() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\Managers\AccountManager.cs:ligne 96
   à Stump.Core.Timers.TimedTimerEntry.Trigger() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Timers\TimedTimerEntry.cs:ligne 128
   à Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback(Object state) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Threading\SelfRunningTaskPool.cs:ligne 223. 
-------------Error at 04/17/2020 15:23:50------------- 

-------------Error at 04/17/2020 15:24:09------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 15:24:09------------- 

-------------Warn at 04/17/2020 15:24:09------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 15:24:09------------- 

-------------Error at 04/17/2020 15:24:21------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 15:24:21------------- 

-------------Error at 04/17/2020 15:24:31------------- 
 Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback -> 
	Exception raised when processing TimerEntry Stump.Core.Timers.TimedTimerEntry (Callback = Stump.Server.AuthServer.Managers.AccountManager.Void RefreshBans(), Delay = 60000) in Stump.Server.BaseServer.Benchmark.BenchmarkedTaskPool : System.InvalidOperationException: Connection must be valid and open.
   à MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   à MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   à MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   à MySql.Data.MySqlClient.MySqlCommand.CheckState()
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   à System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   à Stump.ORM.Database.<Query>d__71`1.MoveNext() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 783
   à System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   à System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   à Stump.Server.AuthServer.Managers.AccountManager.RefreshBans() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\Managers\AccountManager.cs:ligne 96
   à Stump.Core.Timers.TimedTimerEntry.Trigger() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Timers\TimedTimerEntry.cs:ligne 128
   à Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback(Object state) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Threading\SelfRunningTaskPool.cs:ligne 223. 
-------------Error at 04/17/2020 15:24:31------------- 

-------------Error at 04/17/2020 15:24:31------------- 
 Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback -> 
	Exception raised when processing TimerEntry Stump.Core.Timers.TimedTimerEntry (Callback = Stump.Server.AuthServer.Managers.AccountManager.Void RefreshBans(), Delay = 60000) in Stump.Server.BaseServer.Benchmark.BenchmarkedTaskPool : System.InvalidOperationException: Connection must be valid and open.
   à MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   à MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   à MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   à MySql.Data.MySqlClient.MySqlCommand.CheckState()
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   à System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   à Stump.ORM.Database.<Query>d__71`1.MoveNext() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 783
   à System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   à System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   à Stump.Server.AuthServer.Managers.AccountManager.RefreshBans() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\Managers\AccountManager.cs:ligne 96
   à Stump.Core.Timers.TimedTimerEntry.Trigger() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Timers\TimedTimerEntry.cs:ligne 128
   à Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback(Object state) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Threading\SelfRunningTaskPool.cs:ligne 223. 
-------------Error at 04/17/2020 15:24:31------------- 

-------------Error at 04/17/2020 15:38:42------------- 
 Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback -> 
	Exception raised when processing TimerEntry Stump.Core.Timers.TimedTimerEntry (Callback = Stump.Server.AuthServer.Managers.AccountManager.Void RefreshBans(), Delay = 60000) in Stump.Server.BaseServer.Benchmark.BenchmarkedTaskPool : MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered during command execution. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered attempting to read the resultset. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Reading from the stream has failed. ---> System.IO.IOException: Impossible de lire les données de la connexion de transport : Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu. ---> System.Net.Sockets.SocketException: Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu
   à System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   à System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   à System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   à System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   à MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   à MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   à MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   à MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   à MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   à MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   à MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   à MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   à MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   à MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   à System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   à Stump.ORM.Database.<Query>d__71`1.MoveNext() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 783
   à System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   à System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   à Stump.Server.AuthServer.Managers.AccountManager.RefreshBans() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\Managers\AccountManager.cs:ligne 96
   à Stump.Core.Timers.TimedTimerEntry.Trigger() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Timers\TimedTimerEntry.cs:ligne 128
   à Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback(Object state) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Threading\SelfRunningTaskPool.cs:ligne 223. 
-------------Error at 04/17/2020 15:38:42------------- 

-------------Error at 04/17/2020 15:39:01------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 15:39:01------------- 

-------------Warn at 04/17/2020 15:39:01------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 15:39:01------------- 

-------------Error at 04/17/2020 15:39:01------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 15:39:01------------- 

-------------Error at 04/17/2020 15:39:22------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 15:39:22------------- 

-------------Warn at 04/17/2020 15:39:22------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 15:39:22------------- 

-------------Error at 04/17/2020 15:39:22------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 15:39:22------------- 

-------------Error at 04/17/2020 15:39:33------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 15:39:33------------- 

-------------Warn at 04/17/2020 15:39:33------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 15:39:33------------- 

-------------Error at 04/17/2020 15:39:33------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 15:39:33------------- 

-------------Error at 04/17/2020 15:39:43------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 15:39:43------------- 

-------------Warn at 04/17/2020 15:39:43------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 15:39:43------------- 

-------------Error at 04/17/2020 15:39:43------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 15:39:43------------- 

-------------Error at 04/17/2020 15:39:53------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 15:39:53------------- 

-------------Warn at 04/17/2020 15:39:53------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 15:39:53------------- 

-------------Error at 04/17/2020 15:39:53------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 15:39:53------------- 

-------------Error at 04/17/2020 15:40:04------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 15:40:04------------- 

-------------Warn at 04/17/2020 15:40:04------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 15:40:04------------- 

-------------Error at 04/17/2020 15:40:04------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 15:40:04------------- 

-------------Error at 04/17/2020 15:40:14------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 15:40:14------------- 

-------------Warn at 04/17/2020 15:40:14------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 15:40:14------------- 

-------------Error at 04/17/2020 15:40:14------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 15:40:14------------- 

-------------Fatal at 04/17/2020 15:52:59------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Connection must be valid and open.
 Source: MySql.Data -> Void Throw(System.Exception)
 Stack Trace:
   à MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   à MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   à MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   à MySql.Data.MySqlClient.MySqlCommand.CheckState()
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   à Stump.ORM.Database.Update(String tableName, String primaryKeyName, Object poco, Object primaryKeyValue, IEnumerable`1 columns) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 1457
   à Stump.ORM.Database.Update(Object poco, Object primaryKeyValue, IEnumerable`1 columns) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 1488
   à Stump.ORM.Database.Update(Object poco) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 1478
   à Stump.Server.AuthServer.Managers.WorldServerManager.RemoveWorld(WorldServer world) dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\Managers\WorldServerManager.cs:ligne 267
   à Stump.Server.AuthServer.IPC.IPCClient.Disconnect() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\IPC\IPCClient.cs:ligne 363
   à Stump.Server.AuthServer.IPC.IPCClient.ProcessReceive(Object sender, SocketAsyncEventArgs e) dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\IPC\IPCClient.cs:ligne 172
   à System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   à System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object ignored)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   à System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   à System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP) 
-------------Fatal at 04/17/2020 15:52:59------------- 

-------------Error at 04/17/2020 15:53:14------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 15:53:14------------- 

-------------Fatal at 04/17/2020 15:53:25------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 15:53:25------------- 

-------------Fatal at 04/17/2020 15:53:25------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 15:53:25------------- 

-------------Fatal at 04/17/2020 15:53:25------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 15:53:25------------- 

-------------Error at 04/17/2020 15:53:40------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 15:53:40------------- 

-------------Fatal at 04/17/2020 15:53:40------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 15:53:40------------- 

-------------Fatal at 04/17/2020 15:53:40------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 15:53:40------------- 

-------------Fatal at 04/17/2020 15:53:40------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 15:53:40------------- 

-------------Error at 04/17/2020 15:53:54------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 15:53:54------------- 

-------------Fatal at 04/17/2020 15:53:54------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 15:53:54------------- 

-------------Fatal at 04/17/2020 15:53:54------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 15:53:54------------- 

-------------Fatal at 04/17/2020 15:53:54------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 15:53:54------------- 

-------------Error at 04/17/2020 15:54:09------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 15:54:09------------- 

-------------Fatal at 04/17/2020 15:54:09------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 15:54:09------------- 

-------------Fatal at 04/17/2020 15:54:09------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 15:54:09------------- 

-------------Fatal at 04/17/2020 15:54:09------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 15:54:09------------- 

-------------Error at 04/17/2020 15:54:24------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 15:54:24------------- 

-------------Error at 04/17/2020 16:10:06------------- 
 Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback -> 
	Failed to execute message Stump.Server.AuthServer.IPC.IPCClient+<>c__DisplayClass46_0.<ProcessMessage>b__0 : MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.Server.AuthServer.IPC.IPCOperations.InitializeDatabase() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\IPC\IPCOperations.cs:ligne 94
   à Stump.Server.AuthServer.IPC.IPCOperations..ctor(IPCClient ipcClient) dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\IPC\IPCOperations.cs:ligne 42
   à Stump.Server.AuthServer.IPC.IPCClient.<>c__DisplayClass46_0.<ProcessMessage>b__0() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\IPC\IPCClient.cs:ligne 303
   à Stump.Core.Threading.Message.Execute() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Threading\Messages.cs:ligne 70
   à Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback(Object state) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Threading\SelfRunningTaskPool.cs:ligne 190 
-------------Error at 04/17/2020 16:10:06------------- 

-------------Error at 04/17/2020 16:10:26------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 16:10:26------------- 

-------------Warn at 04/17/2020 16:10:26------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 16:10:26------------- 

-------------Error at 04/17/2020 16:10:37------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 16:10:37------------- 

-------------Error at 04/17/2020 16:10:37------------- 
 Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback -> 
	Exception raised when processing TimerEntry Stump.Core.Timers.TimedTimerEntry (Callback = Stump.Server.AuthServer.Managers.AccountManager.Void RefreshBans(), Delay = 60000) in Stump.Server.BaseServer.Benchmark.BenchmarkedTaskPool : System.InvalidOperationException: Connection must be valid and open.
   à MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   à MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   à MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   à MySql.Data.MySqlClient.MySqlCommand.CheckState()
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   à System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   à Stump.ORM.Database.<Query>d__71`1.MoveNext() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 783
   à System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   à System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   à Stump.Server.AuthServer.Managers.AccountManager.RefreshBans() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\Managers\AccountManager.cs:ligne 96
   à Stump.Core.Timers.TimedTimerEntry.Trigger() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Timers\TimedTimerEntry.cs:ligne 128
   à Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback(Object state) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Threading\SelfRunningTaskPool.cs:ligne 223. 
-------------Error at 04/17/2020 16:10:37------------- 

-------------Error at 04/17/2020 16:10:37------------- 
 Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback -> 
	Exception raised when processing TimerEntry Stump.Core.Timers.TimedTimerEntry (Callback = Stump.Server.AuthServer.Managers.AccountManager.Void RefreshBans(), Delay = 60000) in Stump.Server.BaseServer.Benchmark.BenchmarkedTaskPool : System.InvalidOperationException: Connection must be valid and open.
   à MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   à MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   à MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   à MySql.Data.MySqlClient.MySqlCommand.CheckState()
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   à System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   à Stump.ORM.Database.<Query>d__71`1.MoveNext() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 783
   à System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   à System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   à Stump.Server.AuthServer.Managers.AccountManager.RefreshBans() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\Managers\AccountManager.cs:ligne 96
   à Stump.Core.Timers.TimedTimerEntry.Trigger() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Timers\TimedTimerEntry.cs:ligne 128
   à Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback(Object state) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Threading\SelfRunningTaskPool.cs:ligne 223. 
-------------Error at 04/17/2020 16:10:37------------- 

-------------Error at 04/17/2020 16:10:37------------- 
 Stump.Server.BaseServer.Network.HandledMessage`1.Execute -> 
	[Handler : ServerSelectionMessage] Force disconnection of client <127.0.0.1> (aze) : MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts. ---> System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.Net.Sockets.SocketException: Hôte inconnu
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open()
---> (Exception interne #0) System.Net.Sockets.SocketException (0x80004005): Hôte inconnu
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---

   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.Database.Update(String tableName, String primaryKeyName, Object poco, Object primaryKeyValue, IEnumerable`1 columns) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 1457
   à Stump.ORM.Database.Update(String tableName, String primaryKeyName, Object poco, IEnumerable`1 columns) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 1468
   à Stump.ORM.Database.Update(String tableName, String primaryKeyName, Object poco) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 1463
   à Stump.ORM.Database.Save(String tableName, String primaryKeyName, Object poco) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 1619
   à Stump.ORM.Database.Save(Object poco) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 1626
   à Stump.Server.AuthServer.Network.AuthClient.SaveNow() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\Network\AuthClient.cs:ligne 98
   à Stump.Server.AuthServer.Handlers.Connection.ConnectionHandler.SendSelectServerData(AuthClient client, WorldServer world) dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\Handlers\Connection\ConnectionHandler.cs:ligne 313
   à Stump.Server.AuthServer.Handlers.Connection.ConnectionHandler.HandleServerSelectionMessage(AuthClient client, ServerSelectionMessage message) dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\Handlers\Connection\ConnectionHandler.cs:ligne 295
   à (Object , AuthClient , Message )
   à Stump.Core.Threading.Message3`3.Execute() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Threading\Messages.cs:ligne 389
   à Stump.Server.BaseServer.Network.HandledMessage`1.Execute() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.BaseServer\Network\HandledMessage.cs:ligne 26 
-------------Error at 04/17/2020 16:10:37------------- 

-------------Error at 04/17/2020 16:10:47------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 16:10:47------------- 

-------------Warn at 04/17/2020 16:10:47------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 16:10:47------------- 

-------------Error at 04/17/2020 16:10:47------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 16:10:47------------- 

-------------Fatal at 04/17/2020 16:10:53------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Connection must be valid and open.
 Source: MySql.Data -> Void Throw(System.Exception)
 Stack Trace:
   à MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   à MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   à MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   à MySql.Data.MySqlClient.MySqlCommand.CheckState()
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   à Stump.ORM.Database.Update(String tableName, String primaryKeyName, Object poco, Object primaryKeyValue, IEnumerable`1 columns) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 1457
   à Stump.ORM.Database.Update(Object poco, Object primaryKeyValue, IEnumerable`1 columns) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 1488
   à Stump.ORM.Database.Update(Object poco) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 1478
   à Stump.Server.AuthServer.Managers.WorldServerManager.RemoveWorld(WorldServer world) dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\Managers\WorldServerManager.cs:ligne 267
   à Stump.Server.AuthServer.IPC.IPCClient.Disconnect() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\IPC\IPCClient.cs:ligne 363
   à Stump.Server.AuthServer.IPC.IPCClient.ProcessReceive(Object sender, SocketAsyncEventArgs e) dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\IPC\IPCClient.cs:ligne 172
   à System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   à System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object ignored)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   à System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   à System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP) 
-------------Fatal at 04/17/2020 16:10:53------------- 

-------------Error at 04/17/2020 16:10:59------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 16:10:59------------- 

-------------Warn at 04/17/2020 16:10:59------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 16:10:59------------- 

-------------Error at 04/17/2020 16:10:59------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 16:10:59------------- 

-------------Error at 04/17/2020 16:11:08------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 16:11:08------------- 

-------------Fatal at 04/17/2020 16:11:10------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 16:11:10------------- 

-------------Fatal at 04/17/2020 16:11:10------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 16:11:10------------- 

-------------Fatal at 04/17/2020 16:11:10------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 16:11:10------------- 

-------------Error at 04/17/2020 16:11:25------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 16:11:25------------- 

-------------Fatal at 04/17/2020 16:11:36------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 16:11:36------------- 

-------------Fatal at 04/17/2020 16:11:36------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 16:11:36------------- 

-------------Fatal at 04/17/2020 16:11:36------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 16:11:36------------- 

-------------Error at 04/17/2020 16:11:51------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 16:11:51------------- 

-------------Fatal at 04/17/2020 16:12:02------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 16:12:02------------- 

-------------Fatal at 04/17/2020 16:12:02------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 16:12:02------------- 

-------------Fatal at 04/17/2020 16:12:02------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 16:12:02------------- 

-------------Error at 04/17/2020 16:12:17------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 16:12:17------------- 

-------------Fatal at 04/17/2020 16:12:17------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 16:12:17------------- 

-------------Fatal at 04/17/2020 16:12:17------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 16:12:17------------- 

-------------Fatal at 04/17/2020 16:12:17------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 16:12:17------------- 

-------------Error at 04/17/2020 16:12:31------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 16:12:31------------- 

-------------Fatal at 04/17/2020 16:12:31------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 16:12:31------------- 

-------------Fatal at 04/17/2020 16:12:31------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 16:12:31------------- 

-------------Fatal at 04/17/2020 16:12:31------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 16:12:31------------- 

-------------Error at 04/17/2020 16:12:46------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 16:12:46------------- 

-------------Fatal at 04/17/2020 16:12:58------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 16:12:58------------- 

-------------Fatal at 04/17/2020 16:12:58------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 16:12:58------------- 

-------------Fatal at 04/17/2020 16:12:58------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 16:12:58------------- 

-------------Error at 04/17/2020 16:13:12------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 16:13:12------------- 

-------------Error at 04/17/2020 16:23:32------------- 
 Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback -> 
	Exception raised when processing TimerEntry Stump.Core.Timers.TimedTimerEntry (Callback = Stump.Server.AuthServer.Managers.AccountManager.Void RefreshBans(), Delay = 60000) in Stump.Server.BaseServer.Benchmark.BenchmarkedTaskPool : MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered during command execution. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered attempting to read the resultset. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Reading from the stream has failed. ---> System.IO.IOException: Impossible de lire les données de la connexion de transport : Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu. ---> System.Net.Sockets.SocketException: Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu
   à System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   à System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   à System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   à System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   à MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   à MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   à MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   à MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   à MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   à MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   à MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   à MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   à MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   à MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   à System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   à Stump.ORM.Database.<Query>d__71`1.MoveNext() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 783
   à System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   à System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   à Stump.Server.AuthServer.Managers.AccountManager.RefreshBans() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\Managers\AccountManager.cs:ligne 96
   à Stump.Core.Timers.TimedTimerEntry.Trigger() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Timers\TimedTimerEntry.cs:ligne 128
   à Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback(Object state) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Threading\SelfRunningTaskPool.cs:ligne 223. 
-------------Error at 04/17/2020 16:23:32------------- 

-------------Error at 04/17/2020 16:23:52------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 16:23:52------------- 

-------------Warn at 04/17/2020 16:23:52------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 16:23:52------------- 

-------------Error at 04/17/2020 16:23:52------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 16:23:52------------- 

-------------Error at 04/17/2020 16:23:52------------- 
 Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback -> 
	Exception raised when processing TimerEntry Stump.Core.Timers.TimedTimerEntry (Callback = Stump.Server.AuthServer.Managers.AccountManager.Void RefreshBans(), Delay = 60000) in Stump.Server.BaseServer.Benchmark.BenchmarkedTaskPool : System.InvalidOperationException: Connection must be valid and open.
   à MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   à MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   à MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   à MySql.Data.MySqlClient.MySqlCommand.CheckState()
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   à System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   à Stump.ORM.Database.<Query>d__71`1.MoveNext() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 783
   à System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   à System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   à Stump.Server.AuthServer.Managers.AccountManager.RefreshBans() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\Managers\AccountManager.cs:ligne 96
   à Stump.Core.Timers.TimedTimerEntry.Trigger() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Timers\TimedTimerEntry.cs:ligne 128
   à Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback(Object state) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Threading\SelfRunningTaskPool.cs:ligne 223. 
-------------Error at 04/17/2020 16:23:52------------- 

-------------Error at 04/17/2020 16:23:52------------- 
 Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback -> 
	Exception raised when processing TimerEntry Stump.Core.Timers.TimedTimerEntry (Callback = Stump.Server.AuthServer.Managers.AccountManager.Void RefreshBans(), Delay = 60000) in Stump.Server.BaseServer.Benchmark.BenchmarkedTaskPool : System.InvalidOperationException: Connection must be valid and open.
   à MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   à MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   à MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   à MySql.Data.MySqlClient.MySqlCommand.CheckState()
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   à MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   à System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   à Stump.ORM.Database.<Query>d__71`1.MoveNext() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 783
   à System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   à System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   à Stump.Server.AuthServer.Managers.AccountManager.RefreshBans() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\Managers\AccountManager.cs:ligne 96
   à Stump.Core.Timers.TimedTimerEntry.Trigger() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Timers\TimedTimerEntry.cs:ligne 128
   à Stump.Core.Threading.SelfRunningTaskPool.ProcessCallback(Object state) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.Core\Threading\SelfRunningTaskPool.cs:ligne 223. 
-------------Error at 04/17/2020 16:23:52------------- 

-------------Error at 04/17/2020 16:24:02------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 16:24:02------------- 

-------------Warn at 04/17/2020 16:24:02------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 16:24:02------------- 

-------------Error at 04/17/2020 16:24:02------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 16:24:02------------- 

-------------Error at 04/17/2020 16:24:23------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 16:24:23------------- 

-------------Warn at 04/17/2020 16:24:23------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 16:24:23------------- 

-------------Error at 04/17/2020 16:24:23------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 16:24:23------------- 

-------------Error at 04/17/2020 16:24:33------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 16:24:33------------- 

-------------Warn at 04/17/2020 16:24:33------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 16:24:33------------- 

-------------Error at 04/17/2020 16:24:33------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 16:24:33------------- 

-------------Error at 04/17/2020 16:24:43------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 16:24:43------------- 

-------------Warn at 04/17/2020 16:24:43------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 16:24:43------------- 

-------------Error at 04/17/2020 16:24:43------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 16:24:43------------- 

-------------Error at 04/17/2020 16:24:53------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot ping SQL connection : {0} 
-------------Error at 04/17/2020 16:24:53------------- 

-------------Warn at 04/17/2020 16:24:53------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Try to Re-open the connection 
-------------Warn at 04/17/2020 16:24:53------------- 

-------------Error at 04/17/2020 16:24:53------------- 
 Stump.Server.BaseServer.ServerBase.KeepSQLConnectionAlive -> 
	Cannot reopen the SQL connection : {0} 
-------------Error at 04/17/2020 16:24:53------------- 

-------------Error at 04/17/2020 16:25:05------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 16:25:05------------- 

-------------Fatal at 04/17/2020 16:25:05------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 16:25:05------------- 

-------------Fatal at 04/17/2020 16:25:05------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 16:25:05------------- 

-------------Fatal at 04/17/2020 16:25:05------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 16:25:05------------- 

-------------Error at 04/17/2020 16:25:20------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 16:25:20------------- 

-------------Fatal at 04/17/2020 16:25:20------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 16:25:20------------- 

-------------Fatal at 04/17/2020 16:25:20------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 16:25:20------------- 

-------------Fatal at 04/17/2020 16:25:20------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 16:25:20------------- 

-------------Error at 04/17/2020 16:25:34------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 16:25:34------------- 

-------------Fatal at 04/17/2020 16:25:46------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 16:25:46------------- 

-------------Fatal at 04/17/2020 16:25:46------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 16:25:46------------- 

-------------Fatal at 04/17/2020 16:25:46------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 16:25:46------------- 

-------------Error at 04/17/2020 16:26:01------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 16:26:01------------- 

-------------Fatal at 04/17/2020 16:26:12------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 16:26:12------------- 

-------------Fatal at 04/17/2020 16:26:12------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 16:26:12------------- 

-------------Fatal at 04/17/2020 16:26:12------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 16:26:12------------- 

-------------Error at 04/17/2020 16:26:27------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 16:26:27------------- 

-------------Fatal at 04/17/2020 16:26:27------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 16:26:27------------- 

-------------Fatal at 04/17/2020 16:26:27------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 16:26:27------------- 

-------------Fatal at 04/17/2020 16:26:27------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 16:26:27------------- 

-------------Error at 04/17/2020 16:26:41------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 16:26:41------------- 

-------------Fatal at 04/17/2020 16:26:41------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 16:26:41------------- 

-------------Fatal at 04/17/2020 16:26:41------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 16:26:41------------- 

-------------Fatal at 04/17/2020 16:26:41------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 16:26:41------------- 

-------------Error at 04/17/2020 16:26:56------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 16:26:56------------- 

-------------Fatal at 04/17/2020 16:27:07------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 16:27:07------------- 

-------------Fatal at 04/17/2020 16:27:07------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 16:27:07------------- 

-------------Fatal at 04/17/2020 16:27:07------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 16:27:07------------- 

-------------Error at 04/17/2020 16:27:22------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 16:27:22------------- 

-------------Fatal at 04/17/2020 16:27:22------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 16:27:22------------- 

-------------Fatal at 04/17/2020 16:27:22------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 16:27:22------------- 

-------------Fatal at 04/17/2020 16:27:22------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 16:27:22------------- 

-------------Error at 04/17/2020 16:27:36------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 16:27:36------------- 

-------------Fatal at 04/17/2020 16:27:36------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 16:27:36------------- 

-------------Fatal at 04/17/2020 16:27:36------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 16:27:36------------- 

-------------Fatal at 04/17/2020 16:27:36------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 16:27:36------------- 

-------------Error at 04/17/2020 16:27:50------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 16:27:50------------- 

-------------Fatal at 04/17/2020 16:27:51------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 16:27:51------------- 

-------------Fatal at 04/17/2020 16:27:51------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 16:27:51------------- 

-------------Fatal at 04/17/2020 16:27:51------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 16:27:51------------- 

-------------Error at 04/17/2020 16:28:05------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 16:28:05------------- 

-------------Fatal at 04/17/2020 16:28:05------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Unable to connect to any of the specified MySQL hosts.
 Source: MySql.Data -> Void Open()
 Stack Trace:
   à MySql.Data.MySqlClient.NativeDriver.Open()
   à MySql.Data.MySqlClient.Driver.Open()
   à MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   à MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   à MySql.Data.MySqlClient.MySqlPool.GetConnection()
   à MySql.Data.MySqlClient.MySqlConnection.Open()
   à Stump.ORM.Database.OpenSharedConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\PetaPoco.cs:ligne 243
   à Stump.ORM.DatabaseAccessor.OpenConnection(Database database) dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 106
   à Stump.ORM.DatabaseAccessor.OpenConnection() dans C:\Users\Ordinateur\Desktop\Decay 2.51\Core\Stump.ORM\DatabaseAccessor.cs:ligne 140
   à Stump.Server.AuthServer.AuthServer.Initialize() dans C:\Users\Ordinateur\Desktop\Decay 2.51\server\Stump.Server.AuthServer\AuthServer.cs:ligne 109 
-------------Fatal at 04/17/2020 16:28:05------------- 

-------------Fatal at 04/17/2020 16:28:05------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Une ou plusieurs erreurs se sont produites.
 Source: mscorlib -> Void ThrowIfExceptional(Boolean)
 Stack Trace:
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings)
   à MySql.Data.MySqlClient.NativeDriver.Open() 
-------------Fatal at 04/17/2020 16:28:05------------- 

-------------Fatal at 04/17/2020 16:28:06------------- 
 Stump.Server.BaseServer.ServerBase.HandleCrashException -> 
	 Crash Exception : Hôte inconnu
 Source: System -> System.Net.IPHostEntry HostResolutionEndHelper(System.IAsyncResult)
 Stack Trace:
   à System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   à System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) 
-------------Fatal at 04/17/2020 16:28:06------------- 

-------------Error at 04/17/2020 17:50:02------------- 
 Stump.Server.BaseServer.Plugins.PluginManager.LoadAllPlugins -> 
	Cannot load unexistant plugin path ./plugins/ 
-------------Error at 04/17/2020 17:50:02------------- 

